### ISSUE TITLE
Add support for key files.

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/keepass-menubar#7]

**Comment by gustavnikolaj** [comment]
@GRBurst thought you might be interested in this. You kinda needed it to try it out :-) 

Right now, it's a bit rough to start up. After cloning it would be:

```
$ npm install
$ npm start
```

I'm working on packaging it in a more easily installable way - for both Linux and OSX. #2 #3 

https://github.com/gustavnikolaj/keepass-dmenu/issues/12

**Comment by GRBurst** [comment]
Oh nice, that is right - very kind of you! If I find some spare time I will give it a try this week ;-)
